### ISSUE TITLE
画册会不断重复下载第一页

### ISSUE THREAD

**Issue by Misaka13645** [iMyon/pixivPicker#10]
单页插画正常但是画册会不断下载第一页
以及模拟登录好像跪了..要手动复制cookie上去
求大大修复一下qwq

**Comment by tjsky** [comment]
而且下载的图是240X160之类尺寸的封面小图，不是大图。

**Comment by iMyon** [comment]
更新试试

**Comment by Misaka13645** [comment]
可以正常下载了w 多谢大大

**Comment by tjsky** [comment]
@Misaka13645 你可以用了？昨天我还能自己手写cookies用，今天更新后反而不行了。。。

**Comment by Misaka13645** [comment]
@tjsky 正常使用, 我是手动填的cookies
