### ISSUE TITLE
作者大大，新版为什么没法手动登录了？

### ISSUE THREAD

**Issue by tjsky** [iMyon/pixivPicker#11]
模拟登陆跪了，跪了也没事，手动填一下.cookie就行。
更新新版后，手动登录也不行了。

旧版能用的.cookie文件放到新版里，会提示这个
![](http://ww2.sinaimg.cn/large/7dd4b1bbgy1fejo99g3lfj20mi0drabo.jpg)
而且我发现，我放不放.cookie文件他都提示这个。
第一次运行也不会创建范例.cookie文件了。
感觉代码就没去读取这个文件。

苦恼中。。。求教是我操作不对还是哪里出了问题。

**Comment by iMyon** [comment]
命令行执行`npm install`了吗？
顺便码没打好。。编辑一下吧

**Comment by tjsky** [comment]
漏了没注意到参数那里也有密码，我去试试。，谢谢大大

**Comment by tjsky** [comment]
谢谢。。还真是nmp的问题。已经好了
