### ISSUE TITLE
有个奇怪的问题

### ISSUE THREAD

**Issue by tjsky** [iMyon/pixivPicker#14]
简单说就是运行run.bat后，会卡在。模拟登陆 那一步
 ![问题截图](http://ww1.sinaimg.cn/large/7dd4b1bbly1fkaplkwv27j20n90eiq6r.jpg)

系统是win7sp1，node.js是7.9.0，npm是刚升级过。

之前一直是在正常运行的，从9月17日开始出现此问题。

**Comment by iMyon** [comment]
p站被墙了。

**Comment by tjsky** [comment]
@iMyon 额。。。才发现，谢谢解答

**Comment by iMyon** [comment]
dns的问题，你搜索一下吧
