### ISSUE TITLE
卡模拟登录，手动放置cookie会报错。。。。

### ISSUE THREAD

**Issue by 1354961639** [iMyon/pixivPicker#17]
![QQ截图20190312201320](https://user-images.githubusercontent.com/22723142/54199245-69937280-4503-11e9-9030-1b98fb734b2c.png)
卡模拟登录，手动放置cookie会报错。。。。

**Comment by iMyon** [comment]
截图错误把NodeJs降到8.X版本可以暂时用着，有空再改。。
卡登陆的话是众所周知的原因

**Comment by 1354961639** [comment]
感谢回复
