### ISSUE TITLE
貌似模拟登陆又双叒挂掉了

### ISSUE THREAD

**Issue by tjsky** [iMyon/pixivPicker#18]
![image](https://user-images.githubusercontent.com/7272911/60341156-24c31700-99e0-11e9-904b-7a7595342b22.png)
错误截图如上

node 8.11.3，win7sp1 pixivPicker最新版本
今天突然这样了。

**Comment by iMyon** [comment]
P站登陆加了谷歌验证，晚上回去看看

**Comment by iMyon** [comment]
改了登陆方式，你试试看
模拟登陆修改为以下模式：
1. 首先尝试自动登陆
2. 如果触发验证码会弹出浏览器窗口，需要手动填谷歌验证码

PS：这次的模拟登陆用了headless chrome特性，所以**需要本地安装有chrome，且chrome>59**

更新命令：
```shell
git pull
npm install
```
