### ISSUE TITLE
下载出问题啦，P站貌似又双叒叕改什么东西了。。。

### ISSUE THREAD

**Issue by tjsky** [iMyon/pixivPicker#20]
有些图片下载时变变成，文件夹（按照设置被命名）/0.jpg。这样的感觉。（已设置--skipce参数）

![image](https://user-images.githubusercontent.com/7272911/69487893-084ade00-0e9d-11ea-9635-465bb7a9acad.png)
上边那些文件夹，每个文件夹里只会有一张0.jpg图片。

--------
![无标题](https://user-images.githubusercontent.com/7272911/69487941-f87fc980-0e9d-11ea-941a-f52e1e0a1d6a.png)
![image](https://user-images.githubusercontent.com/7272911/69487971-88257800-0e9e-11ea-8803-0fb7267864d4.png)
而且部分图片cmd窗口里显示成功下载，但实际只有个空文件夹出现，图片没下载到。

**Comment by iMyon** [comment]
我这边还算正常：
```
 node ./app.js --url https://www.pixiv.net/ranking.php?format=json&mode=daily&p=1 --skipce
```
![图片](https://user-images.githubusercontent.com/6144630/69489760-997b7e00-0eb8-11ea-9a1d-80de2ce0fab7.png)
```
 node ./app.js --url https://www.pixiv.net/ranking.php?format=json&mode=daily&p=1&date=20191122 --skipce
```
![图片](https://user-images.githubusercontent.com/6144630/69489770-b2842f00-0eb8-11ea-9c31-6ab0e7797415.png)


应该是网络问题导致图片没有下载完全，然后图片完整性检查失败，达到重试次数后触发图集下载（这个逻辑是有点问题，如果跳过图集的话直接置为失败比较合理）

你试试重新跑一下上面两个命令，看看得到的结果和我的截图是否一致

**Comment by tjsky** [comment]
研究了一下，应该就是你说的网络问题导致的。
最近墙的干扰比较严重，代理会有闪断的问题。
在网络条件好的时候，就没有这个现象了。

**Comment by iMyon** [comment]
update  [删除达到重试次数后尝试画册下载的逻辑](https://github.com/iMyon/pixivPicker/commit/78e046d18695759957c459ab6bf43acb70ce7e80)
