### ISSUE TITLE
心塞塞，模拟登陆貌似又跪了

### ISSUE THREAD

**Issue by tjsky** [iMyon/pixivPicker#8]
心塞，模拟登陆又不行了。
只能自己手动获取cookie了。
P站干什么总改登陆嘛，cookie还有过期时间。
![default](https://cloud.githubusercontent.com/assets/7272911/15492599/99a61272-21af-11e6-8adf-cb71321dabce.jpg)

**Comment by iMyon** [comment]
p站估计要整改api了吧，URL比原来看起来规范了不少..
登录网址又变了，而且还加了个动态参数`post_key`

先记录下，这周有闲情再改
从`https://accounts.pixiv.net/login?lang=zh&source=pc&view_type=page&ref=wwwtop_accounts_index`可以直接获取到明文的`api_key`，模拟登录比原来多一个请求应该就行了
